version: '3'

services:

  traefik:
    image: traefik:v2.8
    container_name: traefik

    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - "./services/traefik/traefik.dev.yml:/etc/traefik/traefik.yml"
      - ./services/traefik/acme.json:/acme.json
    restart: always

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`usadba.rockmedia.dev`) && PathPrefix(`/traefik`)
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik-traefik.loadbalancer.server.port=888"

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    command: rabbitmq-server
    restart: always

    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  application:
    image: amo1csync:latest
    container_name: fastapi
    depends_on:
      - rabbitmq
      - redis
    build:
      context: ./
    command: gunicorn app.main:app --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
    volumes:
      - .:/app
    env_file:
      - sync.env
    restart: always
    environment:
      IS_ROOT: 'True'
      BROKER_HOST: rabbitmq
      REDIS_HOST: redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`usadba.rockmedia.dev`)
      - traefik.http.routers.fastapi.tls=true
      - traefik.http.routers.fastapi.tls.certresolver=letsEncrypt
      - traefik.http.services.fastapi-traefik.loadbalancer.server.port=8000

  worker:
    image: amo1csync:latest
    build:
      context: ./
    container_name: worker
    command: dramatiq app.tasks
    restart: always
    environment:
      BROKER_HOST: rabbitmq
      REDIS_HOST: redis
      PYTHONUNBUFFERED: 0
    env_file:
      - sync.env
    depends_on:
      - application
      - rabbitmq
      - redis

  redis:
    image: "redis:7.0.5"
    container_name: redis
    volumes:
      - .services/redis/redis-data:/var/lib/redis
      - .services/redis/redis.conf:/usr/local/etc/redis/redis.conf
