[entryPoints]
[entryPoints.web]
address = ":80"
[entryPoints.web.http.redirections]
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
[entryPoints.websecure]
address = ":443"

[certificatesResolvers.sync.acme]
email = "mpgg2000@gmail.com"
storage = "acme.json"
[certificatesResolvers.sync.acme.httpChallenge]
# used during the challenge
entryPoint = "web"
[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]

[providers]
[providers.docker]
exposedByDefault = false
