[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.web.http.redirections]
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
[entryPoints.https]
address = ":443"

[certificatesResolvers.letsEncrypt.acme]
email = "mpgg2000@gmail.com"
storage = "acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
[certificatesResolvers.sync.acme.httpChallenge]
# used during the challenge
entryPoint = http
[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]

[providers]
[providers.docker]
# endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false
